/**
 * blogs-data.js — Dynamic Blog Registry
 *
 * Instead of hardcoded data, each category has its own articles.json
 * file at blogs/{domain}/articles.json, generated by the Python pipeline.
 *
 * articles.json entry shape:
 * {
 *   id: "blogs/ml/what-is-machine-learning.md",   ← relative path (also used as file)
 *   category: "ml",
 *   title: "...",
 *   description: "...",
 *   date: "YYYY-MM-DD",
 *   tags: ["tag1", "tag2"],
 *   readTime: "8 min",
 *   file: "blogs/ml/what-is-machine-learning.md"
 * }
 */

/* ── Category Metadata ─────────────────────────────────── */
const CATEGORY_META = {
  ml: {
    label: 'Machine Learning',
    shortLabel: 'ML',
    description: 'Algorithms, theory, and applied ML from fundamentals to production.',
    icon: '🧠',
    color: '#7c6af7',
    bgColor: 'rgba(124, 106, 247, 0.12)',
  },
  dl: {
    label: 'Deep Learning',
    shortLabel: 'DL',
    description: 'Neural networks, architectures, training tricks, and modern DL research.',
    icon: '🔬',
    color: '#4fc8b8',
    bgColor: 'rgba(79, 200, 184, 0.12)',
  },
  nlp: {
    label: 'Natural Language Processing',
    shortLabel: 'NLP',
    description: 'Text processing, transformers, LLMs, and language understanding.',
    icon: '📝',
    color: '#e879a0',
    bgColor: 'rgba(232, 121, 160, 0.12)',
  },
  cv: {
    label: 'Computer Vision',
    shortLabel: 'CV',
    description: 'Image processing, object detection, segmentation, and visual AI.',
    icon: '👁️',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.12)',
  },
  genai: {
    label: 'Generative AI',
    shortLabel: 'Gen AI',
    description: 'Diffusion models, LLMs, RAG, agents, and the frontier of AI generation.',
    icon: '✨',
    color: '#a78bfa',
    bgColor: 'rgba(167, 139, 250, 0.12)',
  },
  ainews: {
    label: 'AI News',
    shortLabel: 'AI News',
    description: 'Breaking developments, model releases, and industry analysis.',
    icon: '📡',
    color: '#34d399',
    bgColor: 'rgba(52, 211, 153, 0.12)',
  },
  statistics: {
    label: 'Statistics for AI',
    shortLabel: 'Stats',
    description: 'Probability, statistical tests, distributions, and the math behind ML.',
    icon: '📊',
    color: '#fb923c',
    bgColor: 'rgba(251, 146, 60, 0.12)',
  },
};

const ALL_CATEGORIES = ['ml', 'dl', 'nlp', 'cv', 'genai', 'ainews', 'statistics'];

/* ── Cache ─────────────────────────────────────────────── */
const _cache = {};

const CONTENT_BASE = new URL(window.CONFIG?.CONTENT_BASE_URL || './', window.location.href);

function contentURL(key) {
  if (!/^blogs\/(ml|dl|nlp|cv|genai|ainews|statistics)\/(?:[a-z0-9-]+\.md|articles\.json)$/.test(key)) {
    throw new Error('Invalid article path');
  }
  const url = new URL(key, CONTENT_BASE);
  if (url.origin !== window.location.origin) throw new Error('Content must be hosted with this site');
  return url.href;
}

function validateArticle(article, category) {
  if (!article || article.category !== category || article.id !== article.file) throw new Error('Invalid article');
  contentURL(article.file);
  if (!article.file.startsWith(`blogs/${category}/`) || !article.file.endsWith('.md')) throw new Error('Invalid category path');
  for (const [field, limit] of [['title', 70], ['description', 160]]) {
    if (typeof article[field] !== 'string' || !article[field].trim() || article[field].length > limit) throw new Error('Invalid metadata');
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(article.date) || !Number.isFinite(Date.parse(article.date)) ||
      new Date(article.date).toISOString().slice(0, 10) !== article.date) throw new Error('Invalid date');
  if (!/^\d{1,4} min$/.test(article.readTime)) throw new Error('Invalid reading time');
  if (!Array.isArray(article.tags) || article.tags.length > 10 ||
      article.tags.some(tag => typeof tag !== 'string' || tag.length > 80)) throw new Error('Invalid tags');
  return article;
}

function showLoadError(container, retry, message = 'Articles could not be loaded.') {
  container.replaceChildren();
  const notice = document.createElement('p');
  notice.setAttribute('role', 'alert');
  notice.textContent = message;
  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'btn-ghost-sm';
  button.textContent = 'Retry';
  button.addEventListener('click', retry);
  container.append(notice, button);
}

/* ── Core Fetch ────────────────────────────────────────── */
/**
 * Load articles.json from the Cloudflare R2 bucket.
 * Returns [] if the request fails (i.e. empty category).
 */
async function loadCategoryArticles(cat) {
  if (!ALL_CATEGORIES.includes(cat)) throw new Error('Unknown category');
  if (_cache[cat] !== undefined) return _cache[cat];
  _cache[cat] = (async () => {
    const res = await fetch(contentURL(`blogs/${cat}/articles.json`), {
      credentials: 'omit', cache: 'no-cache', signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) throw new Error(`Article index unavailable (${res.status})`);
    const raw = await res.text();
    if (raw.length > 500000) throw new Error('Article index is too large');
    const data = JSON.parse(raw);
    if (!Array.isArray(data) || data.length > 2000) throw new Error('Invalid article index');
    return data.map(article => validateArticle(article, cat));
  })();
  try {
    return await _cache[cat];
  } catch (error) {
    delete _cache[cat];
    throw error;
  }
}

/**
 * Get articles for a category, sorted by sort order.
 * @param {string} cat  - category key
 * @param {string} sort - 'newest' | 'oldest'
 */
async function getBlogsByCategory(cat, sort = 'newest') {
  const articles = await loadCategoryArticles(cat);
  const sorted = [...articles].sort((a, b) =>
    sort === 'newest'
      ? new Date(b.date) - new Date(a.date)
      : new Date(a.date) - new Date(b.date)
  );
  return sorted;
}

/**
 * Get a single blog metadata by its id.
 * The id is generally the relative path "blogs/domain/slug.md" stored in the json.
 */
async function getBlogById(id) {
  contentURL(id);
  // Try to parse category from path "blogs/{cat}/..."
  const parts = id.split('/');
  if (parts.length >= 3) {
    const cat = parts[1];
    if (CATEGORY_META[cat]) {
      const articles = await loadCategoryArticles(cat);
      const found = articles.find(a => a.id === id || a.file === id);
      if (found) return found;
    }
  }

  // Fallback brute force
  for (const cat of Object.keys(CATEGORY_META)) {
    const articles = await loadCategoryArticles(cat);
    const found = articles.find(a => a.id === id || a.file === id);
    if (found) return found;
  }
  return null;
}

/**
 * Get the N most recent articles across all main categories.
 */
async function getRecentBlogs(n = 6) {
  const all = await Promise.all(ALL_CATEGORIES.map(loadCategoryArticles));
  const flat = all.flat();
  flat.sort((a, b) => new Date(b.date) - new Date(a.date));
  return flat.slice(0, n);
}

/**
 * Get total article count across all categories.
 */
async function getTotalCount() {
  const all = await Promise.all(ALL_CATEGORIES.map(loadCategoryArticles));
  return all.reduce((sum, arr) => sum + arr.length, 0);
}

/* ── Formatting ─────────────────────────────────────────── */
function formatDate(dateStr) {
  if (!dateStr) return '';
  const [y, m, d] = dateStr.split('-').map(Number);
  return new Date(y, m - 1, d).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
}
